spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        binder:
          brokers:
            - b-1.int-infra-kafka-msk.lgz3ip.c3.kafka.eu-west-3.amazonaws.com:9092
            - b-2.int-infra-kafka-msk.lgz3ip.c3.kafka.eu-west-3.amazonaws.com:9092
            - b-3.int-infra-kafka-msk.lgz3ip.c3.kafka.eu-west-3.amazonaws.com:9092
      bindings:
        producer-out-0:
          binder: kafka
          destination: dataFactory.dataExchange.notification
          content-type: application/json
        consumer-in-0:
          binder: kafka
          destination: dataFactory.dataExchange.notification
          content-type: application/json
